config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "dotcom#index"

  devise_for :users, controllers: { registrations: 'users/registrations', invitations: 'users/invitations', sessions: 'users/sessions' }

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :rooms
      resources :messages
      resources :users, only: %i[show create]
      resource :paddle, only: [] do
        post :notification
      end
      resource :organization, only: [:show]
      resource :session, only: %i[create destroy update]
    end
  end

  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user

  resources :organizations do
    collection do
      get 'settings'
      get 'integrations'
    end
  end

  resources :messages do
    collection do
      get 'settings'
    end
  end

  resources :rooms, only: [:show, :update, :index] do
    collection do
      get 'appearance_setting'
    end
    resources :messages
  end

  resources :notifications, only: [] do
    collection do
      get 'settings'
    end
  end

  resources :contacts, only: [:create]
  resources :subscriptions, only: [:new, :create, :destroy]

  get '/settings' => 'rooms#settings', as: :settings
  get '/request-a-demo' => 'dotcom#contact_us', as: :contact_us
  get '/features' => 'dotcom#features', as: :features
  resources :terms, only: [] do
    collection do
      get 'terms_of_service'
      get 'privacy_policy'
    end
  end
end

app/models/notification.rb
class Notification < ApplicationRecord
  include EmailHandler

  belongs_to :resource, polymorphic: true, optional: true
  belongs_to :user

  self.inheritance_column = :_type_disabled

  after_create_commit -> {
    broadcast_append_later_to(
      "notifications_channel:#{user.id}",
      target: "notifications",
      partial: 'notifications/invitation_notification',
      locals: { notification: self }
    )
  }

  NOTIFICATION_TYPES_MAP = {
    new_organization: 'new_organization',
    new_message: 'new_message',
  }
  NOTIFICATION_TYPES = NOTIFICATION_TYPES_MAP.values

  validates :notification_type, inclusion: { in: NOTIFICATION_TYPES }
  validates :notification_type, :resource_type, :resource_id, :user_id, presence: true
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def settings; end
end

app/views/notifications/_invitation_notification.html.erb
<script>
  document.addEventListener("turbo:frame-missing", (event) => {
    const { detail: { response, visit } } = event;
    event.preventDefault();
    visit(response.url);
  });
</script>
<%= turbo_frame_tag notification do %>
<!-- Global notification live region, render this permanently at the end of the document -->
<div data-controller='notification' aria-live="assertive" class="pointer-events-none fixed inset-0 flex items-end px-4 py-6 sm:items-start sm:p-6">
  <div class="flex w-full flex-col items-center space-y-4 sm:items-end">
    <!--
      Notification panel, dynamically insert this into the live region when it needs to be displayed

      Entering: "transform ease-out duration-300 transition"
        From: "translate-y-2 opacity-0 sm:translate-y-0 sm:translate-x-2"
        To: "translate-y-0 opacity-100 sm:translate-x-0"
      Leaving: "transition ease-in duration-100"
        From: "opacity-100"
        To: "opacity-0"
    -->
    <div class="pointer-events-auto w-full max-w-sm rounded-lg bg-white shadow-lg ring-1 ring-black ring-opacity-5">
      <div class="p-4">
        <div class="flex items-start">
          <div class="flex-shrink-0 pt-0.5">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-bell-ring"><path d="M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9"/><path d="M10.3 21a1.94 1.94 0 0 0 3.4 0"/><path d="M4 2C2.8 3.7 2 5.7 2 8"/><path d="M22 8c0-2.3-.8-4.3-2-6"/></svg>
          </div>
          <div class="ml-3 w-0 flex-1">
            <p class="text-sm font-medium text-gray-900"><%= notification.extra["title"] if notification.extra.present?%></p>
            <p class="mt-1 text-sm text-gray-500"><%= notification.extra["description"] if notification.extra.present? %></p>
            <% if notification.extra&.dig("redirect_url").present? %>
              <div class="mt-4 flex">
                <a href="<%= notification.extra&.dig("redirect_url") %>" type="button" class="inline-flex items-center rounded-md bg-cyan-700 px-2.5 py-1.5 text-sm font-semibold text-white shadow-sm hover:bg-cyan-600 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-cyan-700"><%= notification.extra&.dig("cta_button_text") %></a>
              </div>
            <% end %>
          </div>
          <div class="ml-4 flex flex-shrink-0">
            <button data-action="notification#close" type="button" class="inline-flex rounded-md bg-white text-gray-400 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-cyan-600 focus:ring-offset-2">
              <span class="sr-only">Close</span>
              <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                <path d="M6.28 5.22a.75.75 0 00-1.06 1.06L8.94 10l-3.72 3.72a.75.75 0 101.06 1.06L10 11.06l3.72 3.72a.75.75 0 101.06-1.06L11.06 10l3.72-3.72a.75.75 0 00-1.06-1.06L10 8.94 6.28 5.22z" />
              </svg>
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/notifications/settings.html.erb
<!--
// v0 by Vercel.
// https://v0.dev/t/ocyB7Np5Qva
-->
<div class="flex min-h-screen">
  <%= render partial: 'organizations/settings_sidebar', locals: { active_tab: 'notifications' } %>
  <main class="flex-1 px-8 py-2">
    <%= form_for(current_user, as: :user, url: registration_path(:user), html: { method: :put }) do |f| %>
      <div class="grid grid-cols-2 items-center">
        <h1 class="text-2xl font-semibold mb-6">Notifications</h1>
        <div>
          <%= f.button nil, class:"flex items-center min-w-24 bg-gray-600 hover:bg-black float-right text-white text-sm px-2 py-2 rounded" do %>
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2 lucide lucide-save"><path d="M15.2 3a2 2 0 0 1 1.4.6l3.8 3.8a2 2 0 0 1 .6 1.4V19a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2z"/><path d="M17 21v-7a1 1 0 0 0-1-1H8a1 1 0 0 0-1 1v7"/><path d="M7 3v4a1 1 0 0 0 1 1h7"/></svg>
            Save
          <% end %>
        </div>
      </div>
      <div class="flex space-x-8">
        <div class="w-1/3 space-y-4">
          <h2 class="text-lg font-semibold">Notification types</h2>
          <p class="text-muted-foreground">
            Review each type to ensure you're set up to get notification types when you want them
          </p>
        </div>
        <div class="w-2/3 space-y-4">
          <div class="p-4 border rounded-md bg-muted">
            <div class="flex items-center space-x-2">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-circle-alert"><circle cx="12" cy="12" r="10"/><line x1="12" x2="12" y1="8" y2="12"/><line x1="12" x2="12.01" y1="16" y2="16"/></svg>
              <p class="text-destructive">
                Desktop notifications are off. We highly recommend that you turn on desktop notifications so that you
                get alerted of new messages.
              </p>
            </div>
          </div>
          <div class="space-y-2">
            <h3 class="text-sm font-semibold">Desktop</h3>
            <p class="text-muted-foreground">None</p>
          </div>
          <div class="space-y-2">
            <h3 class="text-sm font-semibold">Email notifications</h3>
            <input
              class="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
              placeholder="Enter a valid email"
              type="email"
              value="sameedatif68@gmail.com"
              disabled
            />
          </div>
          <button class="inline-flex items-center justify-center whitespace-nowrap rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 border border-input bg-background hover:bg-accent hover:text-accent-foreground h-10 px-4 py-2 w-full bg-gray-600 text-white hover:bg-black">
            Send test notification
          </button>
        </div>
      </div>
      <div class="flex space-x-8 py-4">
        <div class="w-1/3 space-y-4">
          <h2 class="text-lg font-semibold">Notification triggers</h2>
          <p class="text-muted-foreground">Specify when and how you want notifications sent</p>
        </div>
        <div class="w-2/3 space-y-4">
          <div class="p-4 border rounded-md">
            <div class="space-y-4">
              <div>
                <h3 class="text-sm font-semibold">When you've been assigned to a conversation</h3>
                <div class="space-y-1">
                  <div class="flex items-center">
                      <%=f.check_box :notification_conversation_assigned_email, class: "w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500"%>
                      <%=f.label :notification_conversation_assigned_email, "Email notifications", class:"ms-2 text-sm font-medium text-gray-900 dark:text-gray-300"%>
                  </div>
                </div>
              </div>
              <div>
                <h3 class="text-sm font-semibold">When customer sends a message</h3>
                <p class="text-muted-foreground text-sm">
                  You won't be notified of new messages from conversations assigned to other staff.
                </p>
                <div class="space-y-1">
                  <div class="flex items-center">
                      <%=f.check_box :notification_message_received_email, class: "w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500"%>
                      <%=f.label :notification_message_received_email, "Email notifications", class:"ms-2 text-sm font-medium text-gray-900 dark:text-gray-300"%>
                  </div>
                </div>
              </div>
              <div>
                <h3 class="text-sm font-semibold">When a message has been unread for 15 minutes</h3>
                <p class="text-muted-foreground text-sm">
                  You won't be notified of unread messages from conversations assigned to other staff.
                </p>
                <div class="space-y-1">
                  <div class="flex items-center">
                      <%=f.check_box :notification_message_reminder_email, class: "w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500"%>
                      <%=f.label :notification_message_reminder_email, "Email notifications", class:"ms-2 text-sm font-medium text-gray-900 dark:text-gray-300"%>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </main>
</div>