config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "dotcom#index"

  devise_for :users, controllers: { registrations: 'users/registrations', invitations: 'users/invitations', sessions: 'users/sessions' }

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :rooms
      resources :messages
      resources :users, only: %i[show create]
      resource :paddle, only: [] do
        post :notification
      end
      resource :organization, only: [:show]
      resource :session, only: %i[create destroy update]
    end
  end

  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user

  resources :organizations do
    collection do
      get 'settings'
      get 'integrations'
    end
  end

  resources :messages do
    collection do
      get 'settings'
    end
  end

  resources :rooms, only: [:show, :update, :index] do
    collection do
      get 'appearance_setting'
    end
    resources :messages
  end

  resources :notifications, only: [] do
    collection do
      get 'settings'
    end
  end

  resources :contacts, only: [:create]
  resources :subscriptions, only: [:new, :create, :destroy]

  get '/settings' => 'rooms#settings', as: :settings
  get '/request-a-demo' => 'dotcom#contact_us', as: :contact_us
  get '/features' => 'dotcom#features', as: :features
  resources :terms, only: [] do
    collection do
      get 'terms_of_service'
      get 'privacy_policy'
    end
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  protect_from_forgery with: :null_session, only: [:create] # Or use `protect_from_forgery` only for specific APIs

  def new; end

  def create
    create_paddle_response!
    create_paddle_products!
    paddle_customer = current_user.paddle_customers.find_or_create_by!(customer_information)
    @paddle_subscription = create_paddle_subscription!(paddle_customer)

    render json: { redirect_url: rooms_path }, status: :ok
  end

  def destroy
    current_user.paddle_subscriptions.where(status: 'completed').last.unsubscribe!

    redirect_to rooms_path, notice: "Your request is being processed"
  end

  private

  def customer_information
    customer_information = params.dig("data", "customer").permit!.to_h.transform_keys("id" => "customer_id")
    address_information = customer_information.delete("address")
    address_information.delete("id")
    customer_information.delete("business")
    customer_information.merge!(address_information)
  end

  def create_paddle_products!
    params.dig("data", "items").each do |item|
      paddle_product = item.dig("product").permit!.to_h.transform_keys("id" => "product_id")
      paddle_product.delete("image_url")
      PaddleProduct.find_or_create_by!(paddle_product)
    end
  end

  def create_paddle_subscription!(paddle_customer)
    subscription_information = params.dig("data").except("id", "customer", "items", "settings", "recurring_totals", "custom_data")
    totals =subscription_information.delete("totals").except("balance", "credit")
    payment_method = subscription_information.dig("payment", "method_details").permit!.to_h.transform_keys("type" => "payment_method_type")
    card_details = payment_method.delete("card").transform_keys { |key| "card_#{key}" }
    payload = subscription_information.to_unsafe_h.merge(totals.to_unsafe_h, payment_method, card_details).except("payment")
    obj = current_user.paddle_subscriptions.find_or_initialize_by(payload)
    obj.paddle_customer = paddle_customer

    obj.save!
  end

  def create_paddle_response!
    PaddleCheckoutResponse.create!(
      response: params,
      user_id: current_user.id
    )
  end
end

app/views/subscriptions/new.html.erb
<script>
  function renderPaddle() {
  $(document).ready(function() {
    Paddle.Environment.set("sandbox");
    Paddle.Initialize({
      token: "test_f627afba304d912b93b618bf864", // replace with a client-side token
      checkout: {
        settings: {
          displayMode: "inline",
          frameTarget: "checkout-container",
          frameInitialHeight: "450",
          frameStyle: "width: 100%; min-width: 312px; background-color: transparent; border: none;"
        }
      },
      eventCallback: function(data) {
        if (data.name == "checkout.completed") {
          $.ajax({
            url: '<%= subscriptions_path %>',
            method: 'POST',
            headers: {
              'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
            },
            contentType: 'application/json',
            data: JSON.stringify(data),
            success: function (response) {
              window.location.href = "<%=rooms_path%>";
            },
            error: function (xhr, status, error) {
              console.error('Error:', error);
            }
          });
        }
      }
    });

    // define items
    const monthItemsList = [
      {
        priceId: 'pri_01jcx62qrksfpwranpwa9fh2fd',
        quantity: 1
      },
    ];

    // define items
    const yearItemsList = [
      {
        priceId: 'pri_01jcx64v4z9c25y16sgvk8pefv',
        quantity: 1
      },
    ];

    function slideSection(currentDiv, newDiv) {
      const $currentDiv = $(currentDiv);
      const $newDiv = $(newDiv);
      $currentDiv.hide();
      $newDiv.show();
    }

    // open checkout
    function openCheckout(items){
      Paddle.Checkout.open({
        items: items
      });
    }

    $("#show-monthly").on("click", function() {
      slideSection("#subscription-options", "#card-form")
      openCheckout(monthItemsList);
    });
    $("#show-yearly").on("click", function() {
      slideSection("#subscription-options", "#card-form")
      openCheckout(yearItemsList);
    });
  });
  }

  function on_change(el){
    let selectedOption = el.target.checked;
    console.log(el.target);
    if (selectedOption) {
      document.getElementById('yearly-price').style.display = 'block';
      document.getElementById('monthly-price').style.display = 'none';
    } else {
      document.getElementById('yearly-price').style.display = 'none';
      document.getElementById('monthly-price').style.display = 'block';
    }
  }
</script>

<script src="https://cdn.paddle.com/paddle/v2/paddle.js" onload="renderPaddle()"></script>

<section class="px-4">
  <!-- component -->
  <div class="bg-white">
    <div class="mx-auto max-w-7xl px-6 lg:px-8">

      <div class="p-4 mx-auto mt-16 max-w-2xl sm:mt-20 lg:mx-0 lg:flex lg:max-w-none">
        <div class="px-2 max-w-4xl lg:flex-auto">
          <h3 class="py-4 text-3xl font-bold tracking-tight text-gray-900">Select your Fluent Assist plan</h3>

          <div id="accordion-flush" data-accordion="collapse" data-active-classes="bg-white dark:bg-gray-900 text-gray-900 dark:text-white" data-inactive-classes="text-gray-500 dark:text-gray-400">
            <h2 id="accordion-flush-heading-1">
              <button type="button" class="flex items-center justify-between w-full py-5 font-medium rtl:text-right text-gray-500 border-b border-gray-200 dark:border-gray-700 dark:text-gray-400 gap-3" data-accordion-target="#accordion-flush-body-1" aria-expanded="true" aria-controls="accordion-flush-body-1">
                <span>What is included?</span>
                <svg data-accordion-icon class="w-3 h-3 rotate-180 shrink-0" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 6">
                  <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5 5 1 1 5"/>
                </svg>
              </button>
            </h2>
            <div id="accordion-flush-body-1" class="hidden" aria-labelledby="accordion-flush-heading-1">
              <ul role="list" class="mt-8 grid grid-cols-1 gap-4 text-sm leading-6 text-gray-600 sm:grid-cols-2 sm:gap-6">
                <li class="flex gap-x-3">
                  <svg class="h-6 w-5 flex-none text-cyan-700" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                    <path fill-rule="evenodd" d="M16.704 4.153a.75.75 0 01.143 1.052l-8 10.5a.75.75 0 01-1.127.075l-4.5-4.5a.75.75 0 011.06-1.06l3.894 3.893 7.48-9.817a.75.75 0 011.05-.143z" clip-rule="evenodd"></path>
                  </svg>
                  Integration Support
                </li>
                <li class="flex gap-x-3">
                  <svg class="h-6 w-5 flex-none text-cyan-700" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                    <path fill-rule="evenodd" d="M16.704 4.153a.75.75 0 01.143 1.052l-8 10.5a.75.75 0 01-1.127.075l-4.5-4.5a.75.75 0 011.06-1.06l3.894 3.893 7.48-9.817a.75.75 0 011.05-.143z" clip-rule="evenodd"></path>
                  </svg>
                  Unlimited Translations
                </li>
                <li class="flex gap-x-3">
                  <svg class="h-6 w-5 flex-none text-cyan-700" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                    <path fill-rule="evenodd" d="M16.704 4.153a.75.75 0 01.143 1.052l-8 10.5a.75.75 0 01-1.127.075l-4.5-4.5a.75.75 0 011.06-1.06l3.894 3.893 7.48-9.817a.75.75 0 011.05-.143z" clip-rule="evenodd"></path>
                  </svg>
                  Live chat widget customization
                </li>
                <li class="flex gap-x-3">
                  <svg class="h-6 w-5 flex-none text-cyan-700" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                    <path fill-rule="evenodd" d="M16.704 4.153a.75.75 0 01.143 1.052l-8 10.5a.75.75 0 01-1.127.075l-4.5-4.5a.75.75 0 011.06-1.06l3.894 3.893 7.48-9.817a.75.75 0 011.05-.143z" clip-rule="evenodd"></path>
                  </svg>
                  24/7 Support
                </li>
              </ul>
            </div>
            <h2 id="accordion-flush-heading-2">
              <button type="button" class="flex items-center justify-between w-full py-5 font-medium rtl:text-right text-gray-500 border-b border-gray-200 dark:border-gray-700 dark:text-gray-400 gap-3" data-accordion-target="#accordion-flush-body-2" aria-expanded="false" aria-controls="accordion-flush-body-2">
                <span>So how does the 14-Day free trial work?</span>
                <svg data-accordion-icon class="w-3 h-3 rotate-180 shrink-0" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 6">
                  <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5 5 1 1 5"/>
                </svg>
              </button>
            </h2>
            <div id="accordion-flush-body-2" class="hidden" aria-labelledby="accordion-flush-heading-2">
              <div class="py-5 border-b border-gray-200 dark:border-gray-700">
                <p class="mb-2 text-gray-500 dark:text-gray-400">You can use Fluent Assist for free up to 14 Days, with full access to everything on the plan you sign up for. If you don't cancel within 14 Days, we'll charge you for the plan you selected.</p>
                <p class="text-gray-500 dark:text-gray-400">You can upgrade or downgrade or cancel at any time with just a few clicks.</p>
              </div>
            </div>
            <h2 id="accordion-flush-heading-3">
              <button type="button" class="flex items-center justify-between w-full py-5 font-medium rtl:text-right text-gray-500 border-b border-gray-200 dark:border-gray-700 dark:text-gray-400 gap-3" data-accordion-target="#accordion-flush-body-3" aria-expanded="false" aria-controls="accordion-flush-body-3">
                <span>Why do you need my credit card for the free trial?</span>
                <svg data-accordion-icon class="w-3 h-3 rotate-180 shrink-0" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 6">
                  <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5 5 1 1 5"/>
                </svg>
              </button>
            </h2>
            <div id="accordion-flush-body-3" class="hidden" aria-labelledby="accordion-flush-heading-3">
              <div class="py-5 border-b border-gray-200 dark:border-gray-700">
                <p class="mb-2 text-gray-500 dark:text-gray-400">We require your credit card information to ensure uninterrupted service if you decide to continue using our product after the free trial period ends. It also helps us verify your identity and prevent abuse of the free trial offer. Rest assured, you won’t be charged during the trial period, and you can cancel anytime without incurring any costs.</p>
              </div>
            </div>
          </div>
        </div>
        <div class="-mt-2 p-2 lg:mt-0 lg:w-full lg:max-w-md lg:flex-shrink-0">
          <div class="rounded-2xl bg-gray-50 py-10 text-center ring-1 ring-inset ring-gray-900/5 lg:flex lg:flex-col lg:justify-center lg:py-16">
            <div id="subscription-options" class="mx-auto max-w-xs px-8">
              <div class="flex justify-center mb-3">
                <span class="me-3 text-lg font-medium text-gray-900 dark:text-gray-300">Monthly</span>
                <label class="inline-flex items-center cursor-pointer">
                  <input type="checkbox" value="" class="sr-only peer" oninput="on_change(event)">
                  <div class="relative w-14 h-7 bg-gray-200 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-blue-300 dark:peer-focus:ring-cyan-700 rounded-full peer dark:bg-gray-700 peer-checked:after:translate-x-full rtl:peer-checked:after:-translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-0.5 after:start-[4px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-6 after:w-6 after:transition-all dark:border-gray-600 peer-checked:bg-blue-600"></div>
                </label>
                <span class="ms-3 text-lg font-medium text-gray-900 dark:text-gray-300">Yearly</span>
              </div>
              <div id="monthly-price">
                <p class="text-base font-semibold text-gray-600">Get the best value for money</p>
                <p class="mt-6 flex items-baseline justify-center gap-x-2">
                  <span class="text-5xl font-bold tracking-tight text-gray-900">$5</span>
                  <label class="inline-flex items-center cursor-pointer">
                    <span class="text-sm font-semibold leading-6 tracking-wide text-gray-600">USD</span>
                  </label>
                </p>
                <button id="show-monthly" class="mt-10 block w-full rounded-md bg-cyan-700 px-3 py-2 text-center text-sm font-semibold text-white shadow-sm hover:bg-cyan-600 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-cyan-700">Continue</button>
                <p class="mt-6 text-xs leading-5 text-gray-600">Invoices and receipts available for easy company reimbursement</p>
              </div>
              <div id="yearly-price" style="display: none;">
                <p class="text-base font-semibold text-gray-600">Get the best value for money</p>
                <p class="mt-6 flex items-baseline justify-center gap-x-2">
                  <span class="text-5xl font-bold tracking-tight text-gray-900">$50</span>
                  <label class="inline-flex items-center cursor-pointer">
                    <span class="text-sm font-semibold leading-6 tracking-wide text-gray-600">USD</span>
                  </label>
                </p>
                <button id="show-yearly" class="mt-10 block w-full rounded-md bg-cyan-700 px-3 py-2 text-center text-sm font-semibold text-white shadow-sm hover:bg-cyan-600 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-cyan-700">Continue</button>
                <p class="mt-6 text-xs leading-5 text-gray-600">Invoices and receipts available for easy company reimbursement</p>
              </div>
            </div>
            <div id="card-form" class="checkout-container" style="display: none;"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>