config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "dotcom#index"

  devise_for :users, controllers: { registrations: 'users/registrations', invitations: 'users/invitations', sessions: 'users/sessions' }

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :rooms
      resources :messages
      resources :users, only: %i[show create]
      resource :paddle, only: [] do
        post :notification
      end
      resource :organization, only: [:show]
      resource :session, only: %i[create destroy update]
    end
  end

  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user

  resources :organizations do
    collection do
      get 'settings'
      get 'integrations'
    end
  end

  resources :messages do
    collection do
      get 'settings'
    end
  end

  resources :rooms, only: [:show, :update, :index] do
    collection do
      get 'appearance_setting'
    end
    resources :messages
  end

  resources :notifications, only: [] do
    collection do
      get 'settings'
    end
  end

  resources :contacts, only: [:create]
  resources :subscriptions, only: [:new, :create, :destroy]

  get '/settings' => 'rooms#settings', as: :settings
  get '/request-a-demo' => 'dotcom#contact_us', as: :contact_us
  get '/features' => 'dotcom#features', as: :features
  resources :terms, only: [] do
    collection do
      get 'terms_of_service'
      get 'privacy_policy'
    end
  end
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :organization
  belongs_to :assignee, :class_name => 'User'

  has_many :messages, dependent: :destroy
  has_many :participants, dependent: :destroy

  scope :public_rooms, -> { where(is_private: false) }

  enum status: {
    open: 0, # We have a password for them
    closed: 1 # Shopify user, guest user (we don't have a password for them)
  }

  def participant?(room, user)
    room.participants.where(user: user).any?
  end

  def self.get_name(user)
    "private_#{user.id}"
  end

  def add_user(user)
    participants.find_or_create_by!(user_id: user.id)
  end

  def remove_user(user)
    participants&.find_by(user_id: user.id).destroy
  end

  def other_participant(user)
    participants.where.not(user: user).first
  end
end

app/controllers/api/v1/rooms_controller.rb
module Api
  module V1
    class RoomsController < ApplicationController
      skip_before_action :authenticate, only: %i[create]

      before_action :assign_user
      before_action :fetch_organization

      def create
        puts "params #{params}"
        Room.transaction do
          @room = Room.new(
            is_private: true,
            name: "user_#{@user.id}",
            organization: @organization,
            assignee_id: current_assignee_id || owner_id
          )
          @room.participants << Participant.new(room: @room, user_id: @organization.current_assignee_id || @organization.owner_id)
          @room.participants << Participant.new(room: @room, user_id: @user.id)
          @room.save!
          render json: { message: 'Logged in successfully', room_id:  @room.id, user_id: @user.id }, status: :ok
        end
      end

      def show; end

      private

      def assign_user
        @user = User.find_by(id: params.dig("user_id"))
        return if @user.present?

        @user = User.find_or_create_by!(
          name: params["name"],
          email: params["email"],
          language: JSON.parse(params["language"])["value"],
          user_type: :external,
          confirmed_at: DateTime.current
        )
      end

      def fetch_organization
        @organization = Organization.find_by(website: params[:org_website])
      end
    end
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :declare_room_variables, only: [:show, :index, :update]
  before_action :verify_subscription

  def index
    respond_to do |format|
      format.js
      format.html
    end
  end

  def show
    @other_participant_name = @room.other_participant(current_user).user.name
    @messages = @room.messages
    @room.touch(:read_at)
    @switch_tab = params[:switch_tab] == 'true'
    respond_to do |format|
      format.js
    end
  end

  def update
    @current_room = @first_room = @room = Room.find(params[:id])
    @room.update!(room_params)
    respond_to do |format|
      format.js
    end
  end

  def settings; end

  def appearance_setting; end

  private

  def verify_subscription
    subscription = current_org.owner.paddle_subscriptions.last
    is_owner = current_org.owner == current_user

    if subscription&.status == "past_due" && is_owner
      redirect_to edit_user_registration_path, alert: "Please pay the pending dues before proceeding. For any issues contact support."
    elsif subscription&.status == "past_due" && !is_owner || subscription.blank?
      sign_out(current_user) # Signs out the current user
      redirect_to root_path, notice: "You have been signed out. The organization has pending dues."
    end
  end

  def room_params
    params.require(:room).permit(:name, :read_at, :assignee_id, :status)
  end

  def declare_room_variables
    @rooms = current_org.rooms.joins(:messages).where(filter_params).uniq
    @room_type = (params[:room_status].presence || 'open').to_s.capitalize
    @current_room = @first_room = @room = Room.find_by(id: params[:id]) || @rooms.first
    @message = Message.new(room: @room, user: current_user)
  end

  def filter_params
    default_params = { status: (params[:room_status].presence || 'open') }
    default_params.merge!({assignee_id: current_user.id}) if params[:self_assigned].present?
    default_params.merge!({assignee_id: nil}) if params[:unassigned].present?
    default_params.merge!({read_at: nil}) if params[:unread].present?

    default_params
  end
end

app/views/rooms/_new_room_form.html.erb
<%= form_with model: @room, remote: true, data: { controller: "reset-form", action: "turbo:submit-end->reset-form#reset"} do |f| %>
  <%= f.text_field :name, class: 'form-control', autocomplete: 'off' %>
  <%= f.submit data: {disable_with: false} %>
<% end %>

app/views/rooms/_room.html.erb
<div>
  <%= link_to room.name, room %>
</div>

app/views/rooms/_rooms_list.html.erb
<div id="room-list" class="flex flex-col w-64 border-r">
  <div class="flex items-center justify-between p-4 border-b">
    <span class="font-semibold"><%= @room_type %></span>
  </div>
  <div class="h-full overflow-hidden relative">
    <div class="flex flex-col divide-y h-full overflow-y-auto">
      <% @rooms.each do |room| %>
        <%= button_to room_path(room.id),
          method: :get,
          local: false,
          remote: true,
          params: {switch_tab: 'true'},
          class: "flex flex-row items-center p-4 relative",
          form_class: "hover:bg-muted hover:text-muted-foreground #{room.id == @current_room.id ? 'bg-gray-100 hover:bg-gray-200': 'hover:bg-gray-100'} " do %>
          <%# <div class="absolute text-xs text-gray-500 right-0 top-0 mr-4 mt-3">2 hours ago</div> %>
          <div class="flex items-center justify-center h-10 w-10 rounded-full bg-cyan-600 hover:bg-cyan-700 text-white font-bold flex-shrink-0">
            <%= room.other_participant(current_user)&.user&.name&.first %>
          </div>
          <div class="flex flex-col flex-grow ml-3">
            <div class="text-sm font-medium"><%= room.other_participant(current_user)&.user&.name %></div>
            <div id="room-<%= room.id%>-last-message"class="text-xs truncate w-40"><%= room.messages.last.source_text %></div>
          </div>
          <%# <div class="flex-shrink-0 ml-2 self-end mb-1">
            <span class="flex items-center justify-center h-5 w-5 bg-red-500 text-white text-xs rounded-full">3</span>
          </div> %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/rooms/index.html.erb
<!--
// v0 by Vercel.
// https://v0.dev/t/KLaYcuYMLi5
-->
<script src="https://cdn.jsdelivr.net/npm/intro.js@7.2.0/intro.min.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/intro.js@7.2.0/minified/introjs.min.css">

<div class="flex h-screen">
  <div class="flex flex-col w-64 border-r">
    <div class="flex items-center justify-between p-4 border-b">
      <div class="flex items-center space-x-2">
        <span class="font-semibold"><%= current_user.owned_org.name %></span>
      </div>
    </div>
    <div class="flex flex-col p-4 space-y-2">
      <%= button_to rooms_path,
        method: :get,
        params: {room_status: 'open'},
        form_class: 'rounded-md hover:bg-muted hover:text-muted-foreground hover:bg-gray-100 px-2 py-1 cursor-pointer' do %>
          <div class="flex items-center space-x-2">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="24"
              height="24"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
              class="w-4 h-4"
            >
              <polyline points="22 12 16 12 14 15 10 15 8 12 2 12"></polyline>
              <path d="M5.45 5.11 2 12v6a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-6l-3.45-6.89A2 2 0 0 0 16.76 4H7.24a2 2 0 0 0-1.79 1.11z"></path>
            </svg>
            <span>Open</span>
          </div>
      <% end %>
      <%= button_to rooms_path,
        method: :get,
        params: {room_status: 'closed'},
        form_class: 'rounded-md hover:bg-muted hover:text-muted-foreground hover:bg-gray-100 px-2 py-1 cursor-pointer' do %>
          <div class="flex items-center space-x-2">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="24"
              height="24"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
              class="w-4 h-4"
            >
              <rect width="20" height="5" x="2" y="3" rx="1"></rect>
              <path d="M4 8v11a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8"></path>
              <path d="M10 12h4"></path>
            </svg>
            <span>Closed</span>
          </div>
      <% end %>
    </div>
    <div class="flex flex-col p-4 space-y-2">
      <span class="text-sm text-muted-foreground">Filters</span>
        <%= button_to rooms_path,
          method: :get,
          params: {self_assigned: 'true'},
          form_class: 'rounded-md hover:bg-muted hover:text-muted-foreground hover:bg-gray-100 px-2 py-1 cursor-pointer' do %>
            <div class="flex items-center space-x-2">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                class="w-4 h-4"
              >
                <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2"></path>
                <circle cx="12" cy="7" r="4"></circle>
              </svg>
              <span>Assigned to me</span>
            </div>
        <% end %>
      <%= button_to rooms_path,
        method: :get,
        params: {unassigned: 'true'},
        form_class: 'rounded-md hover:bg-muted hover:text-muted-foreground hover:bg-gray-100 px-2 py-1 cursor-pointer' do %>
          <div class="flex items-center space-x-2">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="24"
              height="24"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
              class="w-4 h-4"
            >
              <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"></path>
              <circle cx="9" cy="7" r="4"></circle>
              <line x1="17" x2="22" y1="8" y2="13"></line>
              <line x1="22" x2="17" y1="8" y2="13"></line>
            </svg>
            <span>Unassigned</span>
          </div>
      <% end %>
      <%= button_to rooms_path,
        method: :get,
        params: {read_at: 'true'},
        form_class: 'rounded-md hover:bg-muted hover:text-muted-foreground hover:bg-gray-100 px-2 py-1 cursor-pointer' do %>
          <div class="flex items-center space-x-2">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="24"
              height="24"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
              class="w-4 h-4"
            >
              <rect width="20" height="16" x="2" y="4" rx="2"></rect>
              <path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7"></path>
            </svg>
            <span>Unread</span>
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="24"
              height="24"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
              class="w-2 h-2 text-blue-500"
            >
              <circle cx="12.1" cy="12.1" r="1"></circle>
            </svg>
          </div>
      <% end %>
    </div>
    <%= button_to settings_path,
        method: :get,
        form_class: 'rounded-md hover:bg-muted hover:text-muted-foreground hover:bg-gray-100 px-2 py-1 cursor-pointer mt-auto ' do %>
          <div class="flex items-center p-4 space-x-2">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="24"
              height="24"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
              class="w-4 h-4"
            >
              <path d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z"></path>
              <circle cx="12" cy="12" r="3"></circle>
            </svg>
            <span>Settings</span>
          </div>
    <% end %>
  </div>
  <div id="room-list" class="flex flex-col w-64 border-r">
    <%= render partial: 'rooms/rooms_list' %>
  </div>
  <div id="room-tab" class="w-full">
    <%= render partial: 'rooms/room_tab', locals: { room: @first_room } if @first_room.present? %>
  </div>
</div>

<script>
  <% if current_user.owned_org == current_org && !current_user.viewed_tutorial %>
    introJs().setOptions({
      steps: [
        {
          title: 'Welcome',
          intro: "Hi 👋 and thanks for signing up. Let's walk you through the basics."
        },
        {
          title: 'Chat list',
          element: document.querySelector('#room-list'),
          intro: 'All your chat messages will show up here.'
        },
        {
          title: 'Chat box',
          element: document.querySelector('#room-tab'),
          intro: 'This is your chat window, where you can talk to your customers.'
        },
        {
          title: 'Chat actions',
          element: document.querySelector('[id^="room-"][id$="-actions-holder"]'),
          intro: 'You can perform chat related actions from here.'
        }
      ]
    }).oncomplete(function(){
        $.ajax({
            url: '<%= user_registration_path %>',
            method: 'PATCH',
            headers: {
              'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
            },
            contentType: 'application/json',
            data: JSON.stringify({
              user: {
                viewed_tutorial: true
              }
            }),
            success: function (response) {
              window.location.href = "<%=rooms_path%>";
            },
            error: function (xhr, status, error) {
              console.error('Error:', error);
            }
          });
      }).start();
  <% end %>
</script>

app/views/rooms/index.js.erb
$("#room-list").html("<%= escape_javascript render(partial: 'rooms/rooms_list') %>");
$("#room-tab").html("<%= escape_javascript render(partial: 'rooms/room_tab', locals: { room: @first_room }) if @first_room.present? %>");

app/views/rooms/new.js.erb
$("#messages").html("<%= escape_javascript render(partial: 'messages/message_box') %>");

app/views/rooms/settings.html.erb
<div class="flex min-h-screen">
  <%= render partial: 'organizations/settings_sidebar', locals: { active_tab: 'overview' } %>
  <main class="flex-1 px-8 py-2">
    <h1 class="text-2xl font-semibold mb-6">Overview</h1>
    <section class="space-y-6">
      <div>
        <h2 class="text-lg font-semibold">Organization settings</h2>
        <p class="text-sm text-muted-foreground">Manage your Organization preferences</p>
        <div class="grid grid-cols-1 gap-4 mt-4 md:grid-cols-2">
          <%= link_to edit_user_registration_path do %>
            <div class="rounded-lg border bg-card text-card-foreground shadow-sm p-4 hover:bg-gray-100 transition-colors" data-v0-t="card">
              <div class="flex items-center mb-2">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="h-5 w-5 mr-2 lucide lucide-user-round-cog"><path d="M2 21a8 8 0 0 1 10.434-7.62"/><circle cx="10" cy="8" r="5"/><circle cx="18" cy="18" r="3"/><path d="m19.5 14.3-.4.9"/><path d="m16.9 20.8-.4.9"/><path d="m21.7 19.5-.9-.4"/><path d="m15.2 16.9-.9-.4"/><path d="m21.7 16.5-.9.4"/><path d="m15.2 19.1-.9.4"/><path d="m19.5 21.7-.4-.9"/><path d="m16.9 15.2-.4-.9"/></svg>

                <h3 class="text-sm font-medium">Account settings</h3>
              </div>
              <p class="text-sm text-muted-foreground">Update your name and password</p>
            </div>
          <% end %>
          <%= link_to settings_organizations_path do %>
            <div class="rounded-lg border bg-card text-card-foreground shadow-sm p-4 hover:bg-gray-100 transition-colors" data-v0-t="card">
              <div class="flex items-center mb-2">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="h-5 w-5 mr-2 lucide lucide-building-2"><path d="M6 22V4a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v18Z"/><path d="M6 12H4a2 2 0 0 0-2 2v6a2 2 0 0 0 2 2h2"/><path d="M18 9h2a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2h-2"/><path d="M10 6h4"/><path d="M10 10h4"/><path d="M10 14h4"/><path d="M10 18h4"/></svg>
                <h3 class="text-sm font-medium">Manage Organization</h3>
              </div>
              <p class="text-sm text-muted-foreground">Preview informaiton, set default chat assignee</p>
            </div>
          <% end %>
          <%= link_to integrations_organizations_path do %>
            <div class="rounded-lg border bg-card text-card-foreground shadow-sm p-4 hover:bg-gray-100 transition-colors" data-v0-t="card">
              <div class="flex items-center mb-2">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="h-5 w-5 mr-2 lucide lucide-blocks"><rect width="7" height="7" x="14" y="3" rx="1"/><path d="M10 21V8a1 1 0 0 0-1-1H4a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-5a1 1 0 0 0-1-1H3"/></svg>
                <h3 class="text-sm font-medium">Manage Integrations</h3>
              </div>
              <p class="text-sm text-muted-foreground">
                Preview plugin information
              </p>
            </div>
          <% end %>
        </div>
      </div>
      <div>
        <h2 class="text-lg font-semibold">Inbox settings</h2>
        <p class="text-sm text-muted-foreground">Personalize your Inbox experience</p>
        <div class="grid grid-cols-1 gap-4 mt-4 md:grid-cols-2">
          <%= link_to settings_notifications_path do %>
            <div class="rounded-lg border bg-card text-card-foreground shadow-sm p-4 hover:bg-gray-100 transition-colors" data-v0-t="card">
              <div class="flex items-center mb-2">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="h-5 w-5 mr-2">
                  <path d="M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9"></path>
                  <path d="M10.3 21a1.94 1.94 0 0 0 3.4 0"></path>
                </svg>
                <h3 class="text-sm font-medium">Notifications</h3>
              </div>
              <p class="text-sm text-muted-foreground">Manage how you receive notifications</p>
            </div>
          <% end %>
          <%= link_to settings_messages_path do %>
            <div class="rounded-lg border bg-card text-card-foreground shadow-sm p-4 hover:bg-gray-100 transition-colors" data-v0-t="card">
              <div class="flex items-center mb-2">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="h-5 w-5 mr-2 lucide lucide-mail-question"><path d="M22 10.5V6a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2v12c0 1.1.9 2 2 2h12.5"/><path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7"/><path d="M18 15.28c.2-.4.5-.8.9-1a2.1 2.1 0 0 1 2.6.4c.3.4.5.8.5 1.3 0 1.3-2 2-2 2"/><path d="M20 22v.01"/></svg>
                <h3 class="text-sm font-medium">Messages preferences</h3>
              </div>
              <p class="text-sm text-muted-foreground">Customize your message entry settings</p>
            </div>
          <% end %>
        </div>
      </div>
      <div>
        <h2 class="text-lg font-semibold">Customer chat settings</h2>
        <p class="text-sm text-muted-foreground">
          Advanced settings for account and messaging capabilities managed in admin
        </p>
        <div class="grid grid-cols-1 gap-4 mt-4 md:grid-cols-2">
          <%= link_to appearance_setting_rooms_path do %>
            <div class="rounded-lg border bg-card text-card-foreground shadow-sm p-4 hover:bg-gray-100 transition-colors" data-v0-t="card">
              <div class="flex items-center mb-2">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="h-5 w-5 mr-2">
                  <path d="m9.06 11.9 8.07-8.06a2.85 2.85 0 1 1 4.03 4.03l-8.06 8.08"></path>
                  <path d="M7.07 14.94c-1.66 0-3 1.35-3 3.02 0 1.33-2.5 1.52-2 2.02 1.08 1.1 2.49 2.02 4 2.02 2.2 0 4-1.8 4-4.04a3.01 3.01 0 0 0-3-3.02z"></path>
                </svg>
                <h3 class="text-sm font-medium">Chat appearance</h3>
              </div>
              <p class="text-sm text-muted-foreground">Customize your online store chat widget</p>
            </div>
          <% end %>
          <%# <div class="rounded-lg border bg-card text-card-foreground shadow-sm p-4 hover:bg-gray-100 transition-colors" data-id="53" data-v0-t="card">
            <div class="flex items-center mb-2" data-id="54">
              <svg data-id="55" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="h-5 w-5 mr-2">
                <circle cx="12" cy="12" r="10"></circle>
                <polyline points="12 6 12 12 16 14"></polyline>
              </svg>
              <h3 class="text-sm font-medium" data-id="56">Availability</h3>
            </div>
            <p class="text-sm text-muted-foreground" data-id="57">Specify the first reply customers automatically get, based on your availability</p>
          </div> %>
        </div>
      </div>
    </section>
  </main>
</div>

app/views/rooms/show.js.erb
<% if @switch_tab %>
  $("#room-tab").html("<%= escape_javascript render(partial: 'rooms/room_tab', locals: { room: @room }) %>");
<% else %>
  $("#messages").html("<%= escape_javascript render(partial: 'messages/message_box') %>");
<% end %>

app/views/rooms/update.js.erb
$("#room-list").html("<%= escape_javascript render(partial: 'rooms/rooms_list') %>");
$("#room-tab").html("<%= escape_javascript render(partial: 'rooms/room_tab', locals: { room: @room }) %>");
window.initFlowbite();